### ISSUE TITLE
how to uninstall

### ISSUE THREAD

**Issue by OPRESEK** [xicor22/Sudo-su-Termux#1]

**Comment by xicor22** [comment]
Delete the sudo file from the bin folder of the termux (/data/data/com.termux/files/usr/bin) 
`rm -rf /data/data/com.termux/files/usr/bin/sudo`
Execute this command and sudo will be removed from your termux.

**Comment by xicor22** [comment]
Delete the sudo file from the bin folder of the termux (/data/data/com.termux/files/usr/bin)
rm -rf /data/data/com.termux/files/usr/bin/sudo
Execute this command and sudo will be removed from your termux.
